import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { GlobalStyle } from '@/styles/global';
import { ThemeProvider } from 'styled-components';
import { defaultTheme } from '@/styles/themes';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ThemeProvider theme={defaultTheme}>
      <GlobalStyle />
      <html lang="en">
        <body className={inter.className}>
          <header>TOPO</header>
          {children}
          <footer>FOOTER</footer>
        </body>
      </html>
    </ThemeProvider>
  )
}
